#############################################################################
# Makefile for building: ../../../../bin/xalm
# Generated by qmake (2.01a) (Qt 4.7.1) on: ?? 7? 19 17:19:22 2017
# Project:  xalm.pro
# Template: app
# Command: /usr/local/qt4/bin/qmake -o Makefile xalm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/qt4/mkspecs/linux-g++ -I. -I/usr/local/qt4/include/QtCore -I/usr/local/qt4/include/QtNetwork -I/usr/local/qt4/include/QtGui -I/usr/local/qt4/include/QtXml -I/usr/local/qt4/include/QtSql -I/usr/local/qt4/include -I../tmp/xalm/moc -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/qt4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/qt4/lib -lQtSql -L/usr/local/qt4/lib -lQtXml -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../tmp/xalm/obj/

####### Files

SOURCES       = main.cpp \
		displaysetting.cpp \
		mainwin.cpp \
		mdichild.cpp \
		alarmchild.cpp \
		eventchild.cpp \
		textchild.cpp \
		wtdlg.cpp \
		remarkdlg.cpp \
		testdlg.cpp \
		alarmevent.cpp ../tmp/xalm/moc/moc_mainwin.cpp \
		../tmp/xalm/moc/moc_alarmchild.cpp \
		../tmp/xalm/moc/moc_eventchild.cpp \
		../tmp/xalm/moc/moc_textchild.cpp \
		../tmp/xalm/moc/moc_wtdlg.cpp \
		../tmp/xalm/moc/moc_testdlg.cpp \
		../tmp/xalm/moc/moc_remarkdlg.cpp \
		qrc_xalm.cpp
OBJECTS       = ../tmp/xalm/obj/main.o \
		../tmp/xalm/obj/displaysetting.o \
		../tmp/xalm/obj/mainwin.o \
		../tmp/xalm/obj/mdichild.o \
		../tmp/xalm/obj/alarmchild.o \
		../tmp/xalm/obj/eventchild.o \
		../tmp/xalm/obj/textchild.o \
		../tmp/xalm/obj/wtdlg.o \
		../tmp/xalm/obj/remarkdlg.o \
		../tmp/xalm/obj/testdlg.o \
		../tmp/xalm/obj/alarmevent.o \
		../tmp/xalm/obj/moc_mainwin.o \
		../tmp/xalm/obj/moc_alarmchild.o \
		../tmp/xalm/obj/moc_eventchild.o \
		../tmp/xalm/obj/moc_textchild.o \
		../tmp/xalm/obj/moc_wtdlg.o \
		../tmp/xalm/obj/moc_testdlg.o \
		../tmp/xalm/obj/moc_remarkdlg.o \
		../tmp/xalm/obj/qrc_xalm.o
DIST          = /usr/local/qt4/mkspecs/common/g++.conf \
		/usr/local/qt4/mkspecs/common/unix.conf \
		/usr/local/qt4/mkspecs/common/linux.conf \
		/usr/local/qt4/mkspecs/qconfig.pri \
		/usr/local/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/qt4/mkspecs/features/qt_functions.prf \
		/usr/local/qt4/mkspecs/features/qt_config.prf \
		/usr/local/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt4/mkspecs/features/default_pre.prf \
		/usr/local/qt4/mkspecs/features/debug.prf \
		/usr/local/qt4/mkspecs/features/default_post.prf \
		/usr/local/qt4/mkspecs/features/unix/thread.prf \
		/usr/local/qt4/mkspecs/features/qt.prf \
		/usr/local/qt4/mkspecs/features/moc.prf \
		/usr/local/qt4/mkspecs/features/warn_on.prf \
		/usr/local/qt4/mkspecs/features/resources.prf \
		/usr/local/qt4/mkspecs/features/uic.prf \
		/usr/local/qt4/mkspecs/features/yacc.prf \
		/usr/local/qt4/mkspecs/features/lex.prf \
		/usr/local/qt4/mkspecs/features/include_source_dir.prf \
		xalm.pro
QMAKE_TARGET  = xalm
DESTDIR       = ../../../../bin/
TARGET        = ../../../../bin/xalm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_wtdlg.h ui_testdlg.h ui_remarkdlg.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../../../../bin/ || $(MKDIR) ../../../../bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: xalm.pro  /usr/local/qt4/mkspecs/linux-g++/qmake.conf /usr/local/qt4/mkspecs/common/g++.conf \
		/usr/local/qt4/mkspecs/common/unix.conf \
		/usr/local/qt4/mkspecs/common/linux.conf \
		/usr/local/qt4/mkspecs/qconfig.pri \
		/usr/local/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/qt4/mkspecs/features/qt_functions.prf \
		/usr/local/qt4/mkspecs/features/qt_config.prf \
		/usr/local/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt4/mkspecs/features/default_pre.prf \
		/usr/local/qt4/mkspecs/features/debug.prf \
		/usr/local/qt4/mkspecs/features/default_post.prf \
		/usr/local/qt4/mkspecs/features/unix/thread.prf \
		/usr/local/qt4/mkspecs/features/qt.prf \
		/usr/local/qt4/mkspecs/features/moc.prf \
		/usr/local/qt4/mkspecs/features/warn_on.prf \
		/usr/local/qt4/mkspecs/features/resources.prf \
		/usr/local/qt4/mkspecs/features/uic.prf \
		/usr/local/qt4/mkspecs/features/yacc.prf \
		/usr/local/qt4/mkspecs/features/lex.prf \
		/usr/local/qt4/mkspecs/features/include_source_dir.prf \
		/usr/local/qt4/lib/libQtSql.prl \
		/usr/local/qt4/lib/libQtCore.prl \
		/usr/local/qt4/lib/libQtXml.prl \
		/usr/local/qt4/lib/libQtGui.prl \
		/usr/local/qt4/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile xalm.pro
/usr/local/qt4/mkspecs/common/g++.conf:
/usr/local/qt4/mkspecs/common/unix.conf:
/usr/local/qt4/mkspecs/common/linux.conf:
/usr/local/qt4/mkspecs/qconfig.pri:
/usr/local/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/qt4/mkspecs/features/qt_functions.prf:
/usr/local/qt4/mkspecs/features/qt_config.prf:
/usr/local/qt4/mkspecs/features/exclusive_builds.prf:
/usr/local/qt4/mkspecs/features/default_pre.prf:
/usr/local/qt4/mkspecs/features/debug.prf:
/usr/local/qt4/mkspecs/features/default_post.prf:
/usr/local/qt4/mkspecs/features/unix/thread.prf:
/usr/local/qt4/mkspecs/features/qt.prf:
/usr/local/qt4/mkspecs/features/moc.prf:
/usr/local/qt4/mkspecs/features/warn_on.prf:
/usr/local/qt4/mkspecs/features/resources.prf:
/usr/local/qt4/mkspecs/features/uic.prf:
/usr/local/qt4/mkspecs/features/yacc.prf:
/usr/local/qt4/mkspecs/features/lex.prf:
/usr/local/qt4/mkspecs/features/include_source_dir.prf:
/usr/local/qt4/lib/libQtSql.prl:
/usr/local/qt4/lib/libQtCore.prl:
/usr/local/qt4/lib/libQtXml.prl:
/usr/local/qt4/lib/libQtGui.prl:
/usr/local/qt4/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile xalm.pro

dist: 
	@$(CHK_DIR_EXISTS) ../tmp/xalm/obj/xalm1.0.0 || $(MKDIR) ../tmp/xalm/obj/xalm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../tmp/xalm/obj/xalm1.0.0/ && $(COPY_FILE) --parents mainwin.h displaysetting.h mdichild.h alarmchild.h eventchild.h textchild.h wtdlg.h testdlg.h remarkdlg.h alarmevent.h ../tmp/xalm/obj/xalm1.0.0/ && $(COPY_FILE) --parents xalm.qrc ../tmp/xalm/obj/xalm1.0.0/ && $(COPY_FILE) --parents main.cpp displaysetting.cpp mainwin.cpp mdichild.cpp alarmchild.cpp eventchild.cpp textchild.cpp wtdlg.cpp remarkdlg.cpp testdlg.cpp alarmevent.cpp ../tmp/xalm/obj/xalm1.0.0/ && $(COPY_FILE) --parents forms/wtdlg.ui forms/testdlg.ui forms/remarkdlg.ui ../tmp/xalm/obj/xalm1.0.0/ && (cd `dirname ../tmp/xalm/obj/xalm1.0.0` && $(TAR) xalm1.0.0.tar xalm1.0.0 && $(COMPRESS) xalm1.0.0.tar) && $(MOVE) `dirname ../tmp/xalm/obj/xalm1.0.0`/xalm1.0.0.tar.gz . && $(DEL_FILE) -r ../tmp/xalm/obj/xalm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: ../tmp/xalm/moc/moc_mainwin.cpp ../tmp/xalm/moc/moc_alarmchild.cpp ../tmp/xalm/moc/moc_eventchild.cpp ../tmp/xalm/moc/moc_textchild.cpp ../tmp/xalm/moc/moc_wtdlg.cpp ../tmp/xalm/moc/moc_testdlg.cpp ../tmp/xalm/moc/moc_remarkdlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../tmp/xalm/moc/moc_mainwin.cpp ../tmp/xalm/moc/moc_alarmchild.cpp ../tmp/xalm/moc/moc_eventchild.cpp ../tmp/xalm/moc/moc_textchild.cpp ../tmp/xalm/moc/moc_wtdlg.cpp ../tmp/xalm/moc/moc_testdlg.cpp ../tmp/xalm/moc/moc_remarkdlg.cpp
../tmp/xalm/moc/moc_mainwin.cpp: mainwin.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) mainwin.h -o ../tmp/xalm/moc/moc_mainwin.cpp

../tmp/xalm/moc/moc_alarmchild.cpp: mdichild.h \
		alarmevent.h \
		alarmchild.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) alarmchild.h -o ../tmp/xalm/moc/moc_alarmchild.cpp

../tmp/xalm/moc/moc_eventchild.cpp: mdichild.h \
		eventchild.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) eventchild.h -o ../tmp/xalm/moc/moc_eventchild.cpp

../tmp/xalm/moc/moc_textchild.cpp: mdichild.h \
		textchild.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) textchild.h -o ../tmp/xalm/moc/moc_textchild.cpp

../tmp/xalm/moc/moc_wtdlg.cpp: ui_wtdlg.h \
		wtdlg.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) wtdlg.h -o ../tmp/xalm/moc/moc_wtdlg.cpp

../tmp/xalm/moc/moc_testdlg.cpp: ui_testdlg.h \
		testdlg.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) testdlg.h -o ../tmp/xalm/moc/moc_testdlg.cpp

../tmp/xalm/moc/moc_remarkdlg.cpp: ui_remarkdlg.h \
		remarkdlg.h
	/usr/local/qt4/bin/moc $(DEFINES) $(INCPATH) remarkdlg.h -o ../tmp/xalm/moc/moc_remarkdlg.cpp

compiler_rcc_make_all: qrc_xalm.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_xalm.cpp
qrc_xalm.cpp: xalm.qrc \
		images/new.png \
		images/remark.png \
		images/alarm.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/local/qt4/bin/rcc -name xalm xalm.qrc -o qrc_xalm.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_wtdlg.h ui_testdlg.h ui_remarkdlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_wtdlg.h ui_testdlg.h ui_remarkdlg.h
ui_wtdlg.h: forms/wtdlg.ui
	/usr/local/qt4/bin/uic forms/wtdlg.ui -o ui_wtdlg.h

ui_testdlg.h: forms/testdlg.ui
	/usr/local/qt4/bin/uic forms/testdlg.ui -o ui_testdlg.h

ui_remarkdlg.h: forms/remarkdlg.ui
	/usr/local/qt4/bin/uic forms/remarkdlg.ui -o ui_remarkdlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

../tmp/xalm/obj/main.o: main.cpp mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/main.o main.cpp

../tmp/xalm/obj/displaysetting.o: displaysetting.cpp displaysetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/displaysetting.o displaysetting.cpp

../tmp/xalm/obj/mainwin.o: mainwin.cpp mdichild.h \
		alarmchild.h \
		alarmevent.h \
		eventchild.h \
		textchild.h \
		testdlg.h \
		ui_testdlg.h \
		wtdlg.h \
		ui_wtdlg.h \
		displaysetting.h \
		mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/mainwin.o mainwin.cpp

../tmp/xalm/obj/mdichild.o: mdichild.cpp mdichild.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/mdichild.o mdichild.cpp

../tmp/xalm/obj/alarmchild.o: alarmchild.cpp alarmevent.h \
		remarkdlg.h \
		ui_remarkdlg.h \
		alarmchild.h \
		mdichild.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/alarmchild.o alarmchild.cpp

../tmp/xalm/obj/eventchild.o: eventchild.cpp eventchild.h \
		mdichild.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/eventchild.o eventchild.cpp

../tmp/xalm/obj/textchild.o: textchild.cpp textchild.h \
		mdichild.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/textchild.o textchild.cpp

../tmp/xalm/obj/wtdlg.o: wtdlg.cpp mdichild.h \
		wtdlg.h \
		ui_wtdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/wtdlg.o wtdlg.cpp

../tmp/xalm/obj/remarkdlg.o: remarkdlg.cpp remarkdlg.h \
		ui_remarkdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/remarkdlg.o remarkdlg.cpp

../tmp/xalm/obj/testdlg.o: testdlg.cpp testdlg.h \
		ui_testdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/testdlg.o testdlg.cpp

../tmp/xalm/obj/alarmevent.o: alarmevent.cpp alarmevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/alarmevent.o alarmevent.cpp

../tmp/xalm/obj/moc_mainwin.o: ../tmp/xalm/moc/moc_mainwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_mainwin.o ../tmp/xalm/moc/moc_mainwin.cpp

../tmp/xalm/obj/moc_alarmchild.o: ../tmp/xalm/moc/moc_alarmchild.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_alarmchild.o ../tmp/xalm/moc/moc_alarmchild.cpp

../tmp/xalm/obj/moc_eventchild.o: ../tmp/xalm/moc/moc_eventchild.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_eventchild.o ../tmp/xalm/moc/moc_eventchild.cpp

../tmp/xalm/obj/moc_textchild.o: ../tmp/xalm/moc/moc_textchild.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_textchild.o ../tmp/xalm/moc/moc_textchild.cpp

../tmp/xalm/obj/moc_wtdlg.o: ../tmp/xalm/moc/moc_wtdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_wtdlg.o ../tmp/xalm/moc/moc_wtdlg.cpp

../tmp/xalm/obj/moc_testdlg.o: ../tmp/xalm/moc/moc_testdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_testdlg.o ../tmp/xalm/moc/moc_testdlg.cpp

../tmp/xalm/obj/moc_remarkdlg.o: ../tmp/xalm/moc/moc_remarkdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/moc_remarkdlg.o ../tmp/xalm/moc/moc_remarkdlg.cpp

../tmp/xalm/obj/qrc_xalm.o: qrc_xalm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/xalm/obj/qrc_xalm.o qrc_xalm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

